### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Expertium**
Forgot to make the number of parameters bold

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Why do you make the largest number of parameters bold?

**Comment by Expertium** [comment]
So that the entire row is bold

**Comment by L-M-Sherlock** [comment]
I think it's misleading. Given the same accuracy, model with low complexity is better than model with high complexity. If we make the largest number of parameters bold, it may hint high complexity is better.

**Comment by Expertium** [comment]
Yeah, but right now it looks weird because everything in that top row is bold, except for the number of parameters.
If you think that's ok, feel free to close this.

**Comment by L-M-Sherlock** [comment]
OK.

**Pull request closed without merging**
