### PR TITLE
Add AUC to metrics

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by Expertium** [comment]
Add try/except to script.py as well

**Comment by L-M-Sherlock** [comment]
> Add try/except to script.py as well

Which line do you mean?

**Comment by Expertium** [comment]
try:
        auc = roc_auc_score(y_true=y, y_score=p)
    except:
        auc = 0.5

**Comment by L-M-Sherlock** [comment]
Haven't them?

image

**Comment by Expertium** [comment]
I don't see it

**Comment by Expertium** [comment]
Oh, my bad, you added it in the next commit

**Pull request merged**
