### PR TITLE
Removed misleading phrasing and improved siginificance_table.py.md

### PR DESCRIPTION
**Pull request by Expertium**

### CODE REVIEW

**Comment by Expertium** [comment]
@L-M-Sherlock you can merge this

**Comment by L-M-Sherlock** [comment]
Could you update the image?

**Comment by Expertium** [comment]
Done

**Comment by L-M-Sherlock** [comment]
I mean could you replace the image file in your computer and commit the change. I'm running the benchmark so I can't update the image now. Or I will update the image file tomorrow and merge it.

**Comment by Expertium** [comment]
I've updated the image

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by L-M-Sherlock** [comment]
Fine. I mean the file: https://github.com/open-spaced-repetition/fsrs-benchmark/blob/main/plots/Wilcoxon-19854-collections.png

But it's OK. I will update the file tomorrow.

**Comment by Expertium** [comment]
I don't understand. I just updated it?
EDIT: ah, you mean not the one in readme, it's a different one

**Comment by Expertium** [comment]
Also, there seems to be an inconsistency between how the saved image looks like and how the `plt.show()` image looks like. I kept changing the images all the time because something was off. And even if I remove `bbox_inches='tight'`, the inconsistency remains. Saving the image manually does not produce the same results as saving it with `plt.savefig()`. Don't be surprised if I make a few more pull requests in this repo and in the SM-17 repo.

**Pull request merged**
