### PR TITLE
Mention FSRS-5 presets

### PR DESCRIPTION
**Pull request by Expertium**

### CODE REVIEW

**Comment by Expertium** [comment]
Btw, add FSRS-5 to the images, too

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Comment by L-M-Sherlock** [comment]
> Btw, add FSRS-5 to the images, too

I will add it after the benchmark of FSRS-5-deck is finished.

**Comment by Expertium** [comment]
In that case I recommend also waiting for FSRS-5S (siblings), which I will make once I have the necessary dataset and modified optimizer code so that I can use `sibling_review`

**Comment by L-M-Sherlock** [comment]
Duplicated of #139

**Pull request closed without merging**
